apiVersion: v2
name: falco
description: Mod chart for falco with AVP support
type: application
version: 0.1.0

dependencies:
- name: falco
  version: 6.0.1
  repository: https://falcosecurity.github.io/charts
