falco:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"
  falco:
    http_output:
      enabled: true
      url: http://falco-falcosidekick:2801/
  falcosidekick:
    enabled: true
    webui:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: falco.<path:secret/data/infra#domain>
          paths:
          - path: /
    config:
      loki:
        hostport: http://loki.monitoring:3100
        customheaders: "X-Scope-OrgID:krieg"
        extraLabels: "from"
        grafanaDashboard:
          enabled: false
