falcosecurity:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"
  falcosidekick:
    enabled: true
    fullfqdn: true
    webui:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: falco.<path:secret/data/infra#domain>
          paths:
          - path: /
